# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='availabilities',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='user_list',
        ),
        migrations.AddField(
            model_name='calendar',
            name='name',
            field=models.CharField(default='My channel', max_length=20),
        ),
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='My channel', max_length=20),
        ),
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(to='schedule.User'),
        ),
    ]
