# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20161126_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
